name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "gregory.tan@tradegecko.com"
        git config --global user.name "Greg"
        git remote set-url origin https://Gregcake:d0ca345f05e882d798ca404addcf85c88fc63a56@github.com/Gregcake/demo.git
        npm run deploy