name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Deploy to GH Pages
      run: |
        git remote set-url origin "https://Gregcake:ea827d0f6e81c092fb5320646be3b44c82d20f3b@github.com/Gregcake/demo.git"
        npm run deploy