name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "gregtanyy@gmail.com"
        git config --global user.name "Gregcake"
        git remote set-url origin https://x-access-token:8e0f9918571cb067852c2c8136faf942e11737a3@github.com/Gregcake/demo.git
        npm run deploy